// ── Modèle de rôle extensible ─────────────────────────────────────────────────────
//
// team     : camp pour les conditions de victoire ("village" | "wolves" | "solo")
// category : groupement UI pour l'écran de sélection des rôles
//
// automationLevel :
//   "full"     = le joueur agit directement dans l'app (délégation possible)
//   "assisted" = le MJ enregistre ce qui s'est passé IRL (ex: vote des loups)
//   "manual"   = le MJ gère entièrement, l'app affiche seulement une consigne
//   "disabled" = mécanique non implémentée, rôle visible mais non sélectionnable
//
// TODO capitaine vote double : automationLevel "manual" → "assisted" quand implémenté

export interface RoleData {
  id: string;
  name: string;
  category: "wolves" | "village" | "special";
  emoji: string;
  description: string;
  defaultCount: number;
  instructions: Record<string, string>;

  // ── Métadonnées d'implémentation ──
  implemented: boolean;         // logique présente dans l'app
  playable: boolean;            // sélectionnable pour une partie
  team: "village" | "wolves" | "solo"; // camp pour les conditions de victoire
  automationLevel: "full" | "assisted" | "manual" | "disabled";
  phase: "setup" | "night" | "day" | "vote" | "death" | "passive";
  timing: string;               // résumé lisible de quand le rôle agit
  needsPlayerAction: boolean;   // le joueur peut agir via l'app (délégation)
  needsGMAction: boolean;       // le MJ doit intervenir dans l'app
  rulesVariantNotes: string;    // variantes connues des règles officielles
}

export const ROLES: RoleData[] = [
  {
    id: "werewolf",
    name: "Loup-Garou",
    category: "wolves",
    emoji: "🐺",
    description: "Chaque nuit, élimine un villageois avec la meute.",
    defaultCount: 2,
    implemented: true,
    playable: true,
    team: "wolves",
    automationLevel: "assisted",
    phase: "night",
    timing: "Chaque nuit",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Ouvre les yeux avec la meute. Désignez une victime en silence au Maître du Jeu.",
      day: "Reste discret. Mêle-toi aux débats pour ne pas être démasqué.",
      vote: "Vote stratégiquement. Évite de te trahir. Tu peux accuser un autre joueur.",
      end: "La partie est terminée. Tu peux révéler ton identité.",
    },
  },
  {
    id: "bigbadwolf",
    name: "Grand Méchant Loup",
    category: "wolves",
    emoji: "🌑",
    description: "Dévore un villageois supplémentaire s'il n'y a eu aucune mort.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "wolves",
    automationLevel: "assisted",
    phase: "night",
    timing: "Nuit où aucun loup n'est mort",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Certaines variantes n'accordent la dévoration supplémentaire que si aucun loup n'est mort depuis le début.",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Ouvre les yeux avec la meute. Si aucune mort cette nuit, tu peux dévorer un joueur supplémentaire.",
      day: "Reste discret parmi les villageois.",
      vote: "Vote pour protéger la meute.",
      end: "La partie est terminée. Tu peux révéler ton identité.",
    },
  },
  {
    id: "seer",
    name: "Voyante",
    category: "special",
    emoji: "🔮",
    description: "Chaque nuit, découvre le rôle d'un joueur.",
    defaultCount: 1,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "full",
    phase: "night",
    timing: "Chaque nuit",
    needsPlayerAction: true,
    needsGMAction: true,
    rulesVariantNotes: "",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Ouvre les yeux en silence. Désigne discrètement un joueur au Maître du Jeu — il te montrera son rôle.",
      day: "Partage tes informations avec prudence. Ne te révèle pas trop tôt.",
      vote: "Utilise tes révélations pour orienter le vote du village.",
      end: "La partie est terminée. Révèle tes découvertes.",
    },
  },
  {
    id: "witch",
    name: "Sorcière",
    category: "special",
    emoji: "⚗️",
    description: "Possède une potion de vie et une potion de mort.",
    defaultCount: 1,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "full",
    phase: "night",
    timing: "Chaque nuit (usage unique par potion)",
    needsPlayerAction: true,
    needsGMAction: true,
    rulesVariantNotes: "Certaines règles permettent à la Sorcière de se sauver elle-même avec la potion de vie.",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Ouvre les yeux. Le MJ te montrera la victime des Loups. Utilises-tu ta potion de vie ? Ta potion de mort sur quelqu'un ?",
      day: "Participe aux débats. Tes potions sont précieuses, ne les gaspille pas.",
      vote: "Aide le village à éliminer la bonne cible.",
      end: "La partie est terminée. Révèle les potions utilisées.",
    },
  },
  {
    id: "hunter",
    name: "Chasseur",
    category: "special",
    emoji: "🏹",
    description: "En mourant, peut éliminer un joueur de son choix.",
    defaultCount: 1,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "full",
    phase: "death",
    timing: "À la mort du Chasseur",
    needsPlayerAction: true,
    needsGMAction: false,
    rulesVariantNotes: "",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Restes endormi. Tu n'as pas d'action nocturne.",
      day: "Participe aux débats normalement.",
      vote: "Si tu meurs (vote ou nuit), tu peux emporter quelqu'un avec toi. Choisis bien.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "cupid",
    name: "Cupidon",
    category: "special",
    emoji: "💘",
    description: "La première nuit, unit deux joueurs par l'amour.",
    defaultCount: 1,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "full",
    phase: "night",
    timing: "Nuit 1 uniquement",
    needsPlayerAction: true,
    needsGMAction: true,
    rulesVariantNotes: "",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Nuit 1 uniquement : ouvre les yeux, désigne deux joueurs — ils seront liés pour toujours. Les nuits suivantes, reste endormi.",
      day: "Agis selon les intérêts de ton camp et de ton amoureux.",
      vote: "Si ton amoureux(se) meurt, tu meurs aussi. Vote pour protéger votre amour.",
      end: "La partie est terminée. Révèle le couple lié.",
    },
  },
  {
    id: "captain",
    name: "Capitaine",
    category: "special",
    emoji: "⚔️",
    description: "Son vote compte double. Désigne son successeur.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "manual", // TODO: passer à "assisted" quand le double vote est automatisé
    phase: "setup",
    timing: "Désigné en début de partie, effet passif au vote",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Le Capitaine compte pour 2 voix lors du vote. À sa mort, il désigne son successeur. Double vote non automatisé — le MJ gère manuellement.",
    instructions: {
      waiting: "La partie n'a pas encore commencé.",
      night: "Reste endormi. Tu n'as pas d'action nocturne.",
      day: "En tant que Capitaine, ton vote comptera double lors du vote.",
      vote: "Ton vote compte double. Tu peux aussi choisir ton successeur si tu venais à mourir.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "littlegirl",
    name: "Petite Fille",
    category: "village",
    emoji: "👧",
    description: "Peut espionner discrètement les Loups la nuit — au risque d'être éliminée si repérée.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "manual",
    phase: "night",
    timing: "Passif nocturne (risqué)",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Si repérée par les Loups en train d'espionner, elle est éliminée à la place de la victime normale. Le MJ gère cette décision.",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Tu peux entrouvrir les yeux discrètement pendant que les Loups jouent. C'est risqué — si un loup te voit, tu seras éliminé(e) à la place de la victime prévue !",
      day: "Partage discrètement tes observations si tu as espionné. Ne te trahis pas.",
      vote: "Aide le village grâce à tes observations nocturnes.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "elder",
    name: "L'Ancien",
    category: "village",
    emoji: "🧙",
    description: "Résiste à la première attaque des Loups. Si éliminé par le village, les pouvoirs spéciaux des villageois disparaissent.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "manual",
    phase: "passive",
    timing: "Passif — résistance à la première attaque nocturne",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Le MJ annonce que l'Ancien survit à la première attaque. Si éliminé par vote, le MJ annonce que tous les pouvoirs spéciaux des villageois sont perdus pour la suite.",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Reste endormi. Tu n'as pas d'action nocturne. Si les loups te ciblent pour la première fois, tu survivras.",
      day: "Tu as résisté à la première attaque — mais la prochaine sera fatale. Attention : si le village te vote, tous les pouvoirs spéciaux de ton camp disparaissent !",
      vote: "Si tu es éliminé(e) par vote du village, les Voyante, Sorcière, Chasseur et autres perdent leurs pouvoirs pour toujours.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "chevalier",
    name: "Chevalier à l'Épée Rouillée",
    category: "village",
    emoji: "⚔️",
    description: "Si les Loups le dévorent, le premier loup à sa gauche dans l'ordre des joueurs meurt la nuit suivante.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "manual",
    phase: "death",
    timing: "À la mort du Chevalier (par les Loups uniquement)",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Le pouvoir ne s'active que si le Chevalier est tué par les Loups (pas par vote). Le MJ note quel loup est visé et l'élimine discrètement la nuit suivante.",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Reste endormi. Tu n'as pas d'action nocturne.",
      day: "Participe aux débats normalement.",
      vote: "Aide le village à trouver les loups.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "deux_soeurs",
    name: "Deux Sœurs",
    category: "village",
    emoji: "👯",
    description: "Jouées en paire (2 cartes). La première nuit, elles ouvrent les yeux ensemble pour se reconnaître.",
    defaultCount: 2,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "manual",
    phase: "night",
    timing: "Nuit 1 uniquement",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Ce rôle doit toujours être joué avec exactement 2 cartes. Le MJ les réveille nuit 1 pour qu'elles se reconnaissent.",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Le MJ t'a révélé l'identité de ta sœur.",
      night: "Nuit 1 uniquement : ouvre les yeux avec ton autre sœur pour vous reconnaître. Les nuits suivantes, reste endormie.",
      day: "Tu sais qui est ton alliée. Coordonnez-vous discrètement pour aider le village.",
      vote: "Vote stratégiquement — tu peux faire confiance à ta sœur.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "trois_freres",
    name: "Trois Frères",
    category: "village",
    emoji: "👨‍👨‍👦",
    description: "Joués en trio (3 cartes). Nuit 1 et les nuits impaires, ils se réveillent ensemble pour se concerter.",
    defaultCount: 3,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "manual",
    phase: "night",
    timing: "Nuit 1, puis nuits impaires",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Ce rôle doit toujours être joué avec exactement 3 cartes. Le MJ les réveille nuit 1, puis chaque nuit impaire (nuit 3, 5…).",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Le MJ t'a révélé l'identité de tes frères.",
      night: "Nuit 1 et nuits impaires (3, 5…) : ouvre les yeux avec tes frères pour vous concerter en silence. Les autres nuits, reste endormi.",
      day: "Tu connais tes deux alliés. Coordonnez-vous pour guider le village.",
      vote: "Vote stratégiquement — tes frères sont de confiance.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "corbeau",
    name: "Corbeau",
    category: "village",
    emoji: "🐦‍⬛",
    description: "Chaque matin, colle anonymement une affiche accusant un joueur — il reçoit 2 votes supplémentaires lors du vote du jour.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "assisted",
    phase: "day",
    timing: "Chaque matin, avant le vote",
    needsPlayerAction: true,
    needsGMAction: true,
    rulesVariantNotes: "L'identité du Corbeau est secrète. Le MJ annonce publiquement l'accusation mais ne révèle pas qui l'a posée.",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Reste endormi. Tu n'as pas d'action nocturne.",
      day: "Choisis un joueur à accuser : il recevra 2 votes supplémentaires lors du vote de ce jour. Reste discret — personne ne doit savoir que tu es le Corbeau.",
      vote: "Ton accusation est en place. Le joueur ciblé a déjà 2 votes contre lui.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "chien_loup",
    name: "Chien-Loup",
    category: "special",
    emoji: "🐕",
    description: "Au début de la partie, choisit secrètement son camp : Villageois ou Loup-Garou.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "assisted",
    phase: "setup",
    timing: "Début de partie (avant la 1ère nuit)",
    needsPlayerAction: true,
    needsGMAction: false,
    rulesVariantNotes: "S'il choisit les Loups, il rejoint la meute dès la 1ère nuit et gagne avec eux. S'il choisit le Village, il reste un simple villageois.",
    instructions: {
      waiting: "Tu dois choisir ton camp avant que la partie commence. Choisis maintenant — cette décision est définitive.",
      night: "Tu joues pour le camp que tu as choisi.",
      day: "Agis conformément à ton camp choisi.",
      vote: "Vote pour ton camp.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "servante_devouee",
    name: "Servante Dévouée",
    category: "village",
    emoji: "🧹",
    description: "Quand un joueur est éliminé par vote, elle peut récupérer secrètement sa carte et jouer son rôle.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "manual",
    phase: "vote",
    timing: "Après chaque élimination par vote",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "La Servante prend la carte face cachée — personne ne sait quel rôle elle a récupéré. Elle ne peut utiliser ce pouvoir qu'une seule fois.",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Reste endormi. Tu n'as pas d'action nocturne.",
      day: "Si quelqu'un est éliminé par le village, tu peux récupérer sa carte en secret. Le MJ te le permet discrètement.",
      vote: "Observe qui sera éliminé — tu pourras peut-être récupérer son rôle.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "idiot_village",
    name: "Idiot du Village",
    category: "village",
    emoji: "🤡",
    description: "Si le village vote pour l'éliminer, il survit — mais perd définitivement son droit de vote.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "assisted",
    phase: "vote",
    timing: "Quand il est élu par le vote",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "L'Idiot ne perd son vote que la première fois qu'il est élu. Les fois suivantes, il est éliminé normalement.",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Reste endormi. Tu n'as pas d'action nocturne.",
      day: "Participe aux débats normalement.",
      vote: "Si le village vote contre toi, tu survivras — mais tu perdras ton droit de vote pour toujours.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "bouc_emissaire",
    name: "Bouc Émissaire",
    category: "village",
    emoji: "🐐",
    description: "En cas d'égalité des votes, il est éliminé à la place. Le lendemain, tous doivent voter.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "assisted",
    phase: "vote",
    timing: "En cas d'égalité au vote",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Si plusieurs joueurs sont à égalité et que le Bouc Émissaire est vivant, il est éliminé. S'il n'y a pas de Bouc, personne n'est éliminé.",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Reste endormi. Tu n'as pas d'action nocturne.",
      day: "Participe aux débats. Si les votes sont à égalité, c'est toi qui seras éliminé(e).",
      vote: "Si personne ne se dégage clairement, tu seras sacrifié(e) pour sortir de l'impasse.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "ange",
    name: "Ange",
    category: "special",
    emoji: "😇",
    description: "Gagne seul si le village l'élimine lors du tout premier vote. Sinon, devient un Villageois.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "solo",
    automationLevel: "assisted",
    phase: "vote",
    timing: "Premier vote uniquement",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "L'Ange doit être éliminé lors du 1er vote (Jour 1). S'il survit, il perd son pouvoir et joue comme un Villageois.",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Reste endormi. Tu n'as pas d'action nocturne.",
      day: "Ton seul espoir : convaincre le village de voter contre toi dès le premier vote. C'est ta seule chance de victoire.",
      vote: "Si tu es éliminé(e) lors de CE vote (Jour 1), tu gagnes seul(e) ! Sinon tu deviens un simple Villageois.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "villager",
    name: "Villageois",
    category: "village",
    emoji: "👨‍🌾",
    description: "Un simple villageois sans pouvoir particulier.",
    defaultCount: 3,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "full",
    phase: "passive",
    timing: "—",
    needsPlayerAction: false,
    needsGMAction: false,
    rulesVariantNotes: "",
    instructions: {
      waiting: "La partie n'a pas encore commencé.",
      night: "Dors. Tu n'as aucun pouvoir nocturne.",
      day: "Débats, observe les comportements, cherche les Loups parmi vous.",
      vote: "Vote pour éliminer celui qui te semble le plus suspect.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "joueur_flute",
    name: "Joueur de Flûte",
    category: "special",
    emoji: "🎵",
    description: "Chaque nuit, ensorcelle 2 joueurs. Gagne seul si tous les survivants sont ensorcelés à l'aube.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "solo",
    automationLevel: "assisted",
    phase: "night",
    timing: "Chaque nuit — ensorcelle 2 joueurs",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Les joueurs ensorcelés se réveillent tous ensemble pour se reconnaître. La victoire du Joueur de Flûte est vérifiée à l'aube de chaque nuit.",
    instructions: {
      waiting: "La partie n'a pas encore commencé.",
      night: "Ouvre les yeux. Désigne discrètement 2 joueurs à ensorceler. Montre-leur ensuite qu'ils sont sous ton emprise.",
      day: "Dissimule ton pouvoir. Si tous les survivants sont ensorcelés à l'aube, tu gagnes seul.",
      vote: "Vote stratégiquement pour rester en vie.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "renard",
    name: "Renard",
    category: "village",
    emoji: "🦊",
    description: "Chaque nuit, inspecte un groupe de 3 joueurs. S'il n'y a aucun loup parmi eux, il perd définitivement son pouvoir.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "assisted",
    phase: "night",
    timing: "Chaque nuit (tant que le pouvoir n'est pas perdu)",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Le MJ montre discrètement le résultat au Renard (oui/non). S'il n'y a aucun loup dans le groupe, le Renard perd son flair.",
    instructions: {
      waiting: "La partie n'a pas encore commencé.",
      night: "Ouvre les yeux. Montre discrètement au MJ un groupe de 3 joueurs (toi + 2 voisins, ou 3 joueurs au choix). Il te dira si l'un d'eux est un loup.",
      day: "Utilise ton flair pour orienter les débats, sans révéler ton rôle.",
      vote: "Vote selon tes déductions nocturnes.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "gitane",
    name: "Gitane",
    category: "village",
    emoji: "🔮",
    description: "Une fois par partie, échange secrètement son rôle avec un autre joueur.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "assisted",
    phase: "night",
    timing: "Une fois par partie (nuit)",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "L'échange est secret — personne ne sait que les rôles ont été permutés. La Gitane reçoit l'autre rôle et doit dorénavant jouer selon ses règles.",
    instructions: {
      waiting: "La partie n'a pas encore commencé.",
      night: "Si tu veux utiliser ton pouvoir, montre au MJ le joueur dont tu veux récupérer la carte. Il effectuera l'échange secrètement.",
      day: "Joue selon le rôle que tu as maintenant. Ne révèle pas l'échange.",
      vote: "Vote selon ton camp actuel.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "enfant_sauvage",
    name: "Enfant Sauvage",
    category: "village",
    emoji: "🧒",
    description: "Choisit en secret un modèle au début. Si ce modèle meurt, l'Enfant Sauvage bascule du côté des loups.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "assisted",
    phase: "night",
    timing: "Nuit 1 — choisit son modèle",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Si son modèle est tué par les loups, il se réveille avec eux dès la nuit suivante.",
    instructions: {
      waiting: "La partie n'a pas encore commencé.",
      night: "Ouvre les yeux discrètement et montre au MJ qui est ton modèle. Tu veux imiter cette personne — si elle meurt, tu te rangeras du côté des loups.",
      day: "Observe ton modèle. Si la situation évolue, reste prêt à changer de camp.",
      vote: "Vote selon ton camp actuel.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "sectaire",
    name: "Abominable Sectaire",
    category: "village",
    emoji: "🧿",
    description: "Choisit secrètement un camp au début (village ou loups). Gagne si son camp l'emporte.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "assisted",
    phase: "night",
    timing: "Nuit 1 — choisit son camp",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Il n'a aucun pouvoir particulier — il mise tout sur un camp. S'il choisit les loups, il est compté avec eux.",
    instructions: {
      waiting: "La partie n'a pas encore commencé.",
      night: "Montre discrètement au MJ ton choix de camp : village ou loups. Tu veux que ton camp gagne.",
      day: "Joue selon le camp que tu as choisi, sans te trahir.",
      vote: "Vote dans l'intérêt de ton camp secret.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "juge_begue",
    name: "Juge Bègue",
    category: "village",
    emoji: "⚖️",
    description: "Une fois par partie, peut déclencher un second vote immédiat au cours de la même journée.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "assisted",
    phase: "vote",
    timing: "Une fois par partie, pendant la phase de vote",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Il signale secrètement sa décision au MJ. Le second vote est immédiat et final.",
    instructions: {
      waiting: "La partie n'a pas encore commencé.",
      night: "Dors. Tu n'as pas d'action nocturne.",
      day: "Écoute et observe. Si la situation l'exige, tu pourras forcer un second vote.",
      vote: "Si tu veux utiliser ton pouvoir, fais-le discrètement signe au Maître du Jeu.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "salvateur",
    name: "Salvateur",
    category: "village",
    emoji: "🛡️",
    description: "Chaque nuit, protège un joueur contre les loups. Ne peut pas protéger deux fois de suite la même personne.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "village",
    automationLevel: "assisted",
    phase: "night",
    timing: "Chaque nuit, avant les loups",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Il peut se protéger lui-même, sauf dans certaines variantes.",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Ouvre les yeux. Désigne discrètement au MJ la personne que tu veux protéger cette nuit. Tu ne peux pas protéger deux fois de suite la même personne.",
      day: "Reste discret. Ne révèle pas que tu as un rôle de protection.",
      vote: "Vote pour éliminer le joueur le plus suspect.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "loup_blanc",
    name: "Loup-Garou Blanc",
    category: "wolves",
    emoji: "🐺",
    description: "Loup-Garou qui joue pour lui seul. Une nuit sur deux, il peut éliminer un autre Loup-Garou. Gagne s'il est le dernier survivant.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "wolves",
    automationLevel: "assisted",
    phase: "night",
    timing: "Avec les loups + nuit paire : kill solo",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Il se réveille avec les loups normalement, puis une nuit sur deux (nuits 2, 4, 6…) il se réveille seul pour éliminer un autre loup.",
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Ouvre les yeux avec les loups. Désignez une victime ensemble. Les nuits paires (2, 4, 6…), tu te réveilles ensuite seul pour éliminer un loup.",
      day: "Fais semblant d'être un loup ordinaire. Ton but ultime est d'être le dernier survivant.",
      vote: "Vote comme un loup — mais garde en tête que tes alliés sont aussi tes rivaux.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "infect_pdl",
    name: "Infect Père des Loups",
    category: "wolves",
    emoji: "☣️",
    description: "Une fois par partie, peut infecter la victime des loups au lieu de la tuer — elle devient Loup-Garou.",
    defaultCount: 0,
    implemented: true,
    playable: true,
    team: "wolves",
    automationLevel: "assisted",
    phase: "night",
    timing: "Une fois par partie, après le choix de la victime des loups",
    needsPlayerAction: false,
    needsGMAction: true,
    rulesVariantNotes: "Il ne peut pas infecter la Sorcière si elle a sa potion de vie. L'infection ne peut pas être utilisée la première nuit dans certaines variantes.",
    instructions: {
      waiting: "La partie n'a pas encore commencé.",
      night: "Tu te réveilles avec les loups. Une fois par partie, tu peux infecter la victime choisie plutôt que de la tuer — elle rejoindra secrètement la meute.",
      day: "Reste discret. L'infecté fait maintenant partie des loups mais personne ne le sait.",
      vote: "Vote stratégiquement avec la meute.",
      end: "La partie est terminée.",
    },
  },
];

export const ROLES_MAP: Record<string, RoleData> = Object.fromEntries(ROLES.map((r) => [r.id, r]));
