// Définitions des rôles avec leurs instructions par phase
const ROLES = [
  {
    id: "werewolf",
    name: "Loup-Garou",
    category: "wolves",
    emoji: "🐺",
    description: "Chaque nuit, élimine un villageois avec la meute.",
    defaultCount: 2,
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Ouvre les yeux avec la meute. Désignez une victime en silence au Maître du Jeu.",
      day: "Reste discret. Mêle-toi aux débats pour ne pas être démasqué.",
      vote: "Vote stratégiquement. Évite de te trahir. Tu peux accuser un autre joueur.",
      end: "La partie est terminée. Tu peux révéler ton identité.",
    },
  },
  {
    id: "bigbadwolf",
    name: "Grand Méchant Loup",
    category: "wolves",
    emoji: "🌑",
    description: "Dévore un villageois supplémentaire s'il n'y a eu aucune mort.",
    defaultCount: 0,
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Ouvre les yeux avec la meute. Si aucune mort cette nuit, tu peux dévorer un joueur supplémentaire.",
      day: "Reste discret parmi les villageois.",
      vote: "Vote pour protéger la meute.",
      end: "La partie est terminée. Tu peux révéler ton identité.",
    },
  },
  {
    id: "seer",
    name: "Voyante",
    category: "special",
    emoji: "🔮",
    description: "Chaque nuit, découvre le rôle d'un joueur.",
    defaultCount: 1,
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Ouvre les yeux en silence. Désigne discrètement un joueur au Maître du Jeu — il te montrera son rôle.",
      day: "Partage tes informations avec prudence. Ne te révèle pas trop tôt.",
      vote: "Utilise tes révélations pour orienter le vote du village.",
      end: "La partie est terminée. Révèle tes découvertes.",
    },
  },
  {
    id: "witch",
    name: "Sorcière",
    category: "special",
    emoji: "⚗️",
    description: "Possède une potion de vie et une potion de mort.",
    defaultCount: 1,
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Ouvre les yeux. Le MJ te montrera la victime des Loups. Utilises-tu ta potion de vie ? Ta potion de mort sur quelqu'un ?",
      day: "Participe aux débats. Tes potions sont précieuses, ne les gaspille pas.",
      vote: "Aide le village à éliminer la bonne cible.",
      end: "La partie est terminée. Révèle les potions utilisées.",
    },
  },
  {
    id: "hunter",
    name: "Chasseur",
    category: "special",
    emoji: "🏹",
    description: "En mourant, peut éliminer un joueur de son choix.",
    defaultCount: 1,
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Restes endormi. Tu n'as pas d'action nocturne.",
      day: "Participe aux débats normalement.",
      vote: "Si tu meurs (vote ou nuit), tu peux emporter quelqu'un avec toi. Choisis bien.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "cupid",
    name: "Cupidon",
    category: "special",
    emoji: "💘",
    description: "La première nuit, unit deux joueurs par l'amour.",
    defaultCount: 1,
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Nuit 1 uniquement : ouvre les yeux, désigne deux joueurs — ils seront liés pour toujours. Les nuits suivantes, reste endormi.",
      day: "Agis selon les intérêts de ton camp et de ton amoureux.",
      vote: "Si ton amoureux(se) meurt, tu meurs aussi. Vote pour protéger votre amour.",
      end: "La partie est terminée. Révèle le couple lié.",
    },
  },
  {
    id: "littlegirl",
    name: "Petite Fille",
    category: "village",
    emoji: "👧",
    description: "Peut espionner discrètement les Loups la nuit.",
    defaultCount: 0,
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Tu peux entrouvrir les yeux pendant que les Loups jouent. C'est risqué — si tu es vue, tu meurs !",
      day: "Partage discrètement tes observations si tu as espionné.",
      vote: "Aide le village grâce à tes observations nocturnes.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "elder",
    name: "L'Ancien",
    category: "village",
    emoji: "🧙",
    description: "Résiste à la première attaque des Loups.",
    defaultCount: 0,
    instructions: {
      waiting: "La partie n'a pas encore commencé. Garde ton rôle secret.",
      night: "Reste endormi. Tu n'as pas d'action nocturne.",
      day: "Tu résistes à la première attaque des Loups — mais un deuxième coup te sera fatal.",
      vote: "Si tu es éliminé par vote, les villageois perdent leurs pouvoirs spéciaux !",
      end: "La partie est terminée.",
    },
  },
  {
    id: "villager",
    name: "Villageois",
    category: "village",
    emoji: "👨‍🌾",
    description: "Un simple villageois sans pouvoir particulier.",
    defaultCount: 3,
    instructions: {
      waiting: "La partie n'a pas encore commencé.",
      night: "Dors. Tu n'as aucun pouvoir nocturne.",
      day: "Débats, observe les comportements, cherche les Loups parmi vous.",
      vote: "Vote pour éliminer celui qui te semble le plus suspect.",
      end: "La partie est terminée.",
    },
  },
  {
    id: "captain",
    name: "Capitaine",
    category: "special",
    emoji: "⚔️",
    description: "Son vote compte double. Désigne son successeur.",
    defaultCount: 0,
    instructions: {
      waiting: "La partie n'a pas encore commencé.",
      night: "Reste endormi. Tu n'as pas d'action nocturne.",
      day: "En tant que Capitaine, ton vote comptera double lors du vote.",
      vote: "Ton vote compte double. Tu peux aussi choisir ton successeur si tu venais à mourir.",
      end: "La partie est terminée.",
    },
  },
];

const ROLES_MAP = Object.fromEntries(ROLES.map((r) => [r.id, r]));

module.exports = { ROLES, ROLES_MAP };
